CREATE TABLE Workout (
	Id UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT PK_Users_Id PRIMARY KEY
		CONSTRAINT DF_Users_Id DEFAULT NEWID()
	, [Name] VARCHAR(128) NOT NULL
	, DateTimeBegan DATETIME NOT NULL
	  CONSTRAINT DF_Workout_DateTimeBegan DEFAULT CURRENT_TIMESTAMP 
	, DateTimeFinished DATETIME
)